server:
  port: 8761

eureka:
  # 关闭自我保护模式 （使Client无法续约）
#  server:
#    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
  #  表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server

