eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://peer1:9411  #zipkin查询服务器实例的URL：zipkin server 地址
  sleuth:
    sampler:
      # 表示以100%的概率将链路的数据上传给zipkin server ，默认为0.1
      percentage: 1.0
