eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://peer1:9411  #zipkin查询服务器实例的URL：zipkin server 地址
  sleuth:
    sampler:
      # 表示以100%的概率将链路的数据上传给zipkin server ，默认为0.1
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #禁用超时