spring:
  application:
    name: service-turbine
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
turbine:
  app-config: eureka-client-one,eureka-client-two
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
